source :rubygems

gem 'activerecord'
gem 'rake', '0.9.2'
gem 'hoe'
gem 'pg'
gem 'standalone_migrations'
gem 'clint'
gem 'notes'
gem 'json'
gem 'jsonpretty'
gem 'github'
gem 'github_api'
#gem 'github-v3-api'
gem 'github-api-client'

