# TODO - Convert new_migration to use config/database.yml AS config/database.yml with 'development' as default
development:
  adapter: postgresql
  encoding: unicode
  database: rvm_testdata_development
  host: localhost
  pool: 5
  username: me
  password: me
